id = "roc"
name = "Roc"
description = "Roc language support for Zed"
version = "0.1.0"
schema_version = 1
authors = ["Alf Richter <kuehlboxen.vorgemisch0e@icloud.com>"]
repository = "https://github.com/h2000/zed-roc"
languages = ["languages/roc"]

[grammars.roc]
repository = "https://github.com/lukewilliamboswell/tree-sitter-roc"
commit = "80b6bbe1bab45396db0943db410b97e6f4579801"

[language_servers.roc]
language = "Roc"
name = "Roc Language Server"
